[build]
  publish = "public"

[[redirects]]
  from = "/debug"
  to = "/debug.html"
  status = 200

[[redirects]]
  from = "/denied.html"
  to = "/denied.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html?debug=member"
  status = 200
  force = true
  conditions = { Role = ["member"] }

[[redirects]]
  from = "/*"
  to = "/denied.html?debug=no-role"
  status = 302